* Carne Porco à Alentejana
 :PROPERTIES:
  :source-url: https://leitesculinaria.com/7675/recipes-portuguese-pork-with-clams.html
  :servings: 8
  :prep-time: 30 minutes
  :cook-time: 2-4 hours
  :ready-in: 2 days
  :END:

** Ingredients

- 3 pounds boneless pork shoulder or butt cut into 1-inch (2.5-cm) chunks
- 1/4 cup red pepper paste
- 1 3/4 cups dry white wine
- 6 tablespoons olive oil plus more if needed
- 2 medium yellowonions coarsely choppped
- 3 cloves garlic minced
- 2 pounds Yukon gold potatoes peeled and cut into 1-inch (2.5-cm) cubes
-  Kosher salt and freshly ground black pepper
- 3 1/4 pounds small clams such as cockles, manila, butter, or littlenecks, scrubbed and rinsed
- 1/4 cup chopped fresh cilantro leaves

** Directions

1. In a medium bowl, toss the pork chunks with the red pepper paste. Add the wine and toss again. Cover with plastic wrap and refrigerate for at least 24 hours or up to 36 hours.
2. Position a rack in the middle of the oven and crank up the heat to 400°F (200°C).
3. In a colander set over a large bowl, drain the pork, reserving the marinade. Pat the pork dry with paper towels.
4. In a large pot over medium-high heat, warm 3 tablespoons olive oil. Working in batches, add the pork and cook, stirring occasionally, until browned on all sides, 5 to 7 minutes. Add more oil in between batches, if needed. Transfer the pieces to a plate using a slotted spoon. If the bottom of the pot develops a dark coating, tip in some water in between batches and scrape it up.
5. Lower the heat to medium, add the onion, and cook until soft, about 5 minutes. Add the garlic and cook for 1 minute more.
6. Pour in the reserved marinade, return the pork to the pot, and cook, covered, over low heat until the meat is tender, 1 to 1 1/2 hours. If it looks as if the liquid will burble away, spoon in a bit of water.
7. Meanwhile, in a large bowl, toss the potato cubes with the remaining 3 tablespoons oil, season lightly with salt and with plenty of pepper, and scatter in one layer on a rimmed foil-lined baking sheet. Roast, flipping them once or twice, until golden brown, about 45 minutes.
8. Discard any clams that feel heavy (which means they’re full of sand), have broken shells, or don’t close when tapped.
9. Raise the heat under the pork to high, stir in the clams, cover, and cook until they open, 7 to 10 minutes. Toss out any that refuse to pop open. Taste the broth and season with salt and pepper if needed.
10. To serve, remove half the clams from their shells, and return them to the pot. Toss out the shells. Line the bottom of the serving bowls with the potato cubes, top with the pork and clams and broth, and sprinkle with the cilantro. Have a large bowl at the ready for the shells.
