* Laccha Pyaaz (Onion Salad)
 :PROPERTIES:
  :source-url: https://www.saveur.com/french-braised-chicken-basquaise-recipe/
  :servings: 
  :prep-time: 
  :cook-time: 
  :ready-in: 
  :END:

** Ingredients
- 3 tbsp. extra-virgin olive oil
- 4 small fresh chorizo sausages
- 4 skin-on, boneless chicken breasts (about 8 oz. each), halved crosswise
- Kosher salt and freshly ground pepper
- 6 sprigs thyme
- 2 large garlic cloves, lightly crushed
- 1 bay leaf
- 1 medium yellow onion, halved and thinly sliced (2 cups)
- 1 shallot, halved lengthwise and thinly sliced (1/3 cup)
- 1 medium tomato, finely chopped(3/4 cup)
- 2 tbsp. tomato paste
- 1 cup chicken stock
- 1 1 ⁄2 cups dry white wine
- 10 jarred piquillo peppers, drained and halved lengthwise
- 12 boiled small new potatoes (1 1/2 lb.)
- 1 ⁄4 cup green apple, finely diced, for garnish
- 2 tbsp. finely chopped Italian parsley, for garnish
- 2 tsp. piment d'Espelette or paprika


** Directions

1. Preheat the oven to 450°F
2. In a large Dutch oven or high-sided cast-iron skillet, warm 1 tablespoon oil over medium heat.
3. Add the sausages and cook, turning occasionally, until browned, about 8 minutes. Transfer the sausages to a large plate, cut into 3-inch pieces, and set aside.
4. Add the remaining oil to the pot and raise the heat to high.
5. Season the chicken all over with salt and pepper, then add skin side down to the pan. Tuck the thyme sprigs, garlic, and bay leaf between the pieces.
6. Cook until the skin is browned, 5-7 minutes. Transfer the chicken, thyme, garlic, and bay leaf to the plate with the sausages.
7. In the same pot over medium-high heat, add the onion and shallot and cook, stirring occasionally, until lightly browned, about 5 minutes.
8. Stir in the tomato and cook until the liquid evaporates, about 3 minutes.
9. Add the tomato paste and cook, stirring, for 1 minute.
10. Stir in 1⁄2 cup stock and 1⁄2 teaspoon salt, scraping up the browned bits from the bottom of the pan.
11. Cook until the liquid has mostly evaporated, 5-8 minutes. Return the thyme, garlic, bay leaf, sausages, and chicken (skin side up) to the pot. Transfer to the oven and roast until the chicken is cooked through, about 10 minutes.
12. Transfer the chicken and sausages to a platter.
13. Set the pot back on the stove over medium-high heat. Add the wine, piquillo peppers, and remaining 1 cup stock and bring to a simmer
14. Cook, stirring occasionally, until the liquid is reduced by half, about 10 minutes.
15. Remove from the heat. Return the chicken and sausages to the pot along with the potatoes. Serve directly from the pot or on a platter, sprinkled with the apple, parsley, and piment d'Espelette. 

