* Laccha Pyaaz (Onion Salad)
 :PROPERTIES:
  :source-url: https://www.indianhealthyrecipes.com/onion-salad/#Recipe_Card
  :servings: 8
  :prep-time: 10 minutes
  :cook-time: 10 minutes
  :ready-in: 20 minutes
  :END:

** Ingredients

- 2 medium onions
- 1 green chilli, optional
- 2 sprigs coriander leaves (or 8 to 10 mint leaves)
- 1 lemon, about 3 tablespoons of lemon juice
- 1/2 teaspoon salt
- 1/2 teaspoon red chilli powder
- 1/2 or 3/4 teaspoon of chaat masala
- 1/4 to 1/2 teaspoon of black pepper, crushed

** Directions

1. Rinse onions well under running water and peel them. Flice the whole onion to thin round slices.
2. slit the green chili and deseed.  Chop finely.  Also chop the coriander leaves.
3. Separate the layers to get the onion rings.  Add them to a bowl of very cold water and rest for 10 minutes.  Later drain the water and shake off the onion rings gently to get rid of excess moisture.
4. Add them to a serving bowl.  Squeeze lemon juice and add all the spices -- chaat masala, red chilli powder, black pepper, and salt.
5. Also add the deseeded and chopped green chilies and coriander leaves.  Toss everything well.
6. Taste test and add more spice, salt or lemon juice if required.
7. Serve onion salad with grilled snacks, tandoori appetizers, biryani or with pulao.
