* Massa de Pimentão
 :PROPERTIES:
  :source-url: https://www.thespruceeats.com/how-to-make-massa-de-pimentao-2743365
  :servings: 2 Cups
  :prep-time: 30 minutes
  :cook-time: 20 minutes
  :ready-in: 2 days
  :END:
 
** Ingredients

   - 6 Large Red Bell Peppers
   - Sea salt
   - 6 Tablespoons of Olive Oil

** Directions

*** Salt the Peppers

1. Seed and quarter 4 large red bell peppers. Remove all of the white pulp from the inside.
2. Place the quartered slices of red bell pepper in a glass or ceramic bowl and sprinkle them with 2 tablespoons of coarse salt. Stir it well in order to distribute the salt evenly among the peppers.
3. Leave this bowl, uncovered and at room temperature, for a full 24 hours.

*** Prepare the Pepper for Roasting

1. After sitting for the 24 hours, rinse the salt off of the pepper pieces. Try to get as much of it off as possible and then pat them dry with a clean dishcloth or paper towels.
2. Spread them, in a single layer with the skin side up, on a cookie sheet or large baking pan.

*** Roast the Peppers

1. Heat the broiler.
2. Place the peppers under the broiler and cook them until the skins are charred and dark, which should take about 15 to 20 minutes, but since each oven is different, keep an eye on them.
3. Remove them from the oven and allow them to cool off completely.

*** Remove the Skins from the Peppers

Remove the skins from the pepper pieces. They should come off easily.

*** Purée the Peppers

1. Place the peppers and 2 large cloves of garlic in a food processor and purée them.
2. Add 6 tablespoons of good-quality extra-virgin olive oil, a little at a time, while the machine is running until the mixture has reached the consistency of a fine, creamy paste.

Massa de pimentão will store in the refrigerator for up to 2 weeks in an airtight container. If you think you won’t use it all up in that time, put it into an airtight container and freeze it until you need it.
